version: "3.7"

services:

  pyingestion:
    image: pyingestion
    build:
      context: src
      dockerfile: Dockerfile.ingestion
    command: ["./ingestion.py"]
    volumes:
      - ./src/data:/data
      - ./src/sql:/sql
      - ./src/ingestion:/ingestion # for development purposes, so containers rebuild when we change code
      - ./src/logger:/app/logger
    depends_on:
      database:
        condition: service_healthy


  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=temper_code_test
      - MYSQL_USER=temper_code_test
      - MYSQL_PASSWORD=good_luck
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 15
    restart: always

