version: "3.7"

services:

  pyingestion:
    image: pyingestion
    build:
      context: src
      dockerfile: Dockerfile.ingestion
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        pytest -v | tee ./tests/test_results.log
        python ./ingestion.py
    environment:
      - DATABASE_URL=mysql+asyncmy://temper_code_test:good_luck@database/temper_code_test?charset=utf8mb4

    volumes:
      - ./src/data:/app/data
      - ./src/logger:/app/logger
      - ./src/sql:/app/sql
      - ./src/commons:/app/commons
      - ./src/ingestion:/app/ingestion # for development purposes, so containers rebuild when we change code
      - ./src/tests:/app/tests
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=temper_code_test
      - MYSQL_USER=temper_code_test
      - MYSQL_PASSWORD=good_luck
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 15
    restart: always

