FROM python:3.10

WORKDIR /app

COPY ingestion/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ingestion/ingestion.py ./
COPY sql/ ./sql
COPY logger/ ./logger
COPY commons/ ./commons
COPY tests/ ./tests